/*
Camunda Platform REST API

Testing TaskVariableAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package camundarestgo

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_camundarestgo_TaskVariableAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TaskVariableAPIService DeleteTaskVariable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		httpRes, err := apiClient.TaskVariableAPI.DeleteTaskVariable(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskVariableAPIService GetTaskVariable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		resp, httpRes, err := apiClient.TaskVariableAPI.GetTaskVariable(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskVariableAPIService GetTaskVariableBinary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		resp, httpRes, err := apiClient.TaskVariableAPI.GetTaskVariableBinary(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskVariableAPIService GetTaskVariables", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.TaskVariableAPI.GetTaskVariables(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskVariableAPIService ModifyTaskVariables", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.TaskVariableAPI.ModifyTaskVariables(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskVariableAPIService PutTaskVariable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		httpRes, err := apiClient.TaskVariableAPI.PutTaskVariable(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskVariableAPIService SetBinaryTaskVariable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		httpRes, err := apiClient.TaskVariableAPI.SetBinaryTaskVariable(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
