/*
Camunda Platform REST API

Testing TaskLocalVariableAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package camundarestgo

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_camundarestgo_TaskLocalVariableAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TaskLocalVariableAPIService DeleteTaskLocalVariable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		httpRes, err := apiClient.TaskLocalVariableAPI.DeleteTaskLocalVariable(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskLocalVariableAPIService GetTaskLocalVariable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		resp, httpRes, err := apiClient.TaskLocalVariableAPI.GetTaskLocalVariable(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskLocalVariableAPIService GetTaskLocalVariableBinary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		resp, httpRes, err := apiClient.TaskLocalVariableAPI.GetTaskLocalVariableBinary(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskLocalVariableAPIService GetTaskLocalVariables", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.TaskLocalVariableAPI.GetTaskLocalVariables(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskLocalVariableAPIService ModifyTaskLocalVariables", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.TaskLocalVariableAPI.ModifyTaskLocalVariables(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskLocalVariableAPIService PutTaskLocalVariable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		httpRes, err := apiClient.TaskLocalVariableAPI.PutTaskLocalVariable(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskLocalVariableAPIService SetBinaryTaskLocalVariable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var varName string

		httpRes, err := apiClient.TaskLocalVariableAPI.SetBinaryTaskLocalVariable(context.Background(), id, varName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
